version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "25000:25000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://54.234.59.253
    depends_on:
      - backend
