version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "25000:25000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://backend:25000
    depends_on:
      - backend
